import { NO_PENDING_PERMISSION_WRITES } from './app-permissions';
import { NO_PENDING_CAMERA_WRITES } from './device-camera';
import { DeviceClient } from './types';

/** Inert client returned while no device is selected — module-level so its
 *  identity is stable across renders. */
export const NOOP_DEVICE_CLIENT: DeviceClient = {
  platform: 'ios',
  status: 'idle',
  error: null,
  screen: null,
  fps: 0,
  devices: [],
  logs: [],
  logsEnabled: false,
  attachLogs: () => {},
  detachLogs: () => {},
  clearLogs: () => {},
  events: [],
  eventsEnabled: false,
  attachEvents: () => {},
  detachEvents: () => {},
  clearEvents: () => {},
  activity: null,
  deviceSettings: null,
  deviceSettingsPending: new Set(),
  setDeviceSetting: () => {},
  displayWidthDp: null,
  camera: null,
  cameraPending: NO_PENDING_CAMERA_WRITES,
  cameraError: null,
  setCameraImage: () => {},
  clearCameraImage: () => {},
  accessibility: null,
  accessibilityPending: false,
  accessibilityError: null,
  refreshAccessibility: () => {},
  location: null,
  locationPending: false,
  locationError: null,
  setLocation: () => {},
  clearLocation: () => {},
  permissions: null,
  permissionsPending: NO_PENDING_PERMISSION_WRITES,
  permissionsError: null,
  setPermission: () => {},
  resetPermissions: () => {},
  refreshPermissions: () => {},
  streamCapabilities: null,
  streamSettings: null,
  streamSettingsPending: false,
  updateStreamSettings: () => {},
  streamSource: null,
  streamSourcePending: false,
  streamSourceError: null,
  setStreamSource: () => {},
  setGrpcImageMode: () => {},
  setGrpcEncoder: () => {},
  setGrpcInputSource: () => {},
  streamStats: null,
  setStreamStatsEnabled: () => {},
  webRtcCodec: 'h264',
  setWebRtcCodec: () => {},
  capabilities: {
    deviceSettings: false,
    activity: false,
    events: false,
    camera: false,
    accessibility: false,
    streamSettings: false,
    location: false,
    permissions: false,
  },
  foregroundApp: null,
  videoKind: 'img',
  attachVideo: () => {},
  sendTouch: () => {},
  sendKey: () => false,
  pressButton: () => {},
  reload: () => {},
  rotate: () => {},
  screenshot: async () => null,
  appearance: null,
  setAppearance: () => {},
  hardwareKeyboardConnected: null,
  setHardwareKeyboardConnected: () => {},
  toggleSoftwareKeyboard: () => {},
};
